---
title: 'Biodiversity maps as histograms'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ohibc/src/templates/ohibc_hdr1.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}

knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'figs/',
                      echo = TRUE, message = FALSE, warning = FALSE)

library(raster)
library(data.table)

source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')
  ### includes library(tidyverse); library(stringr); 
  ### dir_M points to ohi directory on Mazu; dir_O points to home dir on Mazu

dir_git <- '~/github/spp_risk_dists'

### goal specific folders and info
dir_setup <- file.path(dir_git, 'data_setup')
dir_data  <- file.path(dir_git, 'data')
dir_o_anx <- file.path(dir_O, 'git-annex/spp_risk_dists')

source(file.path(dir_git, 'data_setup/api_fxns.R'))

```

# Summary

Compare MPAs to biodiversity intactness: 

# Methods

## Histograms of risks

``` {r set up mpa and values dataframe}

mean_rast          <- raster(file.path(dir_git, 'output', 'mean_risk_raster_010deg.tif'))
pct_threat_rast    <- raster(file.path(dir_git, 'output', 'pct_threat_raster_010deg.tif'))
mean_rr_rast       <- raster(file.path(dir_git, 'output', 'mean_rr_risk_raster_010deg.tif'))
pct_threat_rr_rast <- raster(file.path(dir_git, 'output', 'sr_rr_pct_threat_raster_010deg.tif'))
eez_rast           <- raster(file.path(dir_git, 'spatial', 'eez_rast_010_wgs84.tif'))

ncell(mean_rast)
### create dataframe with both unweighted and rr-weighted values in columns 
### for faceting or mapping to aesthetics

risk_df <- data.frame(cell_id    = rep(1:ncell(mean_rast), times = 2),
                      eez        = rep(values(eez_rast), times = 2),
                      mean_risk  = c(values(mean_rast), values(mean_rr_rast)),
                      pct_threat = c(values(pct_threat_rast), values(pct_threat_rr_rast)),
                      wt         = rep(c('unweighted', 'range-rarity'), each = ncell(mean_rast))) %>%
  filter(!is.na(mean_risk)) %>%
  left_join(read_csv(file.path(dir_git, 'spatial/rgn_names.csv')), by = c('eez' = 'rgn_id'))


```

### global

``` {r}

ggplot(risk_df, aes(x = mean_risk, fill = wt, color = wt)) +
  ggtheme_plot() +
  geom_density(alpha = .3, size = .25) +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank()) +
  labs(title = 'risk')

ggplot(risk_df, aes(x = pct_threat, fill = wt, color = wt)) +
  ggtheme_plot() +
  geom_density(alpha = .3, size = .25) +
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank()) +
  labs(title = 'percent threatened')

```

### regional

``` {r}

ggplot(risk_df, aes(x = mean_risk, fill = wt, color = wt)) +
  ggtheme_plot() +
  geom_density(alpha = .3, size = .25) +
  theme(axis.text.y  = element_blank(),
        axis.title.y = element_blank()) +
  facet_wrap( ~ r1_label, scales = 'free_y') +
  labs(title = 'risk')

ggplot(risk_df, aes(x = pct_threat, fill = wt, color = wt)) +
  ggtheme_plot() +
  geom_density(alpha = .3, size = .25) +
  theme(axis.text.y  = element_blank(),
        axis.title.y = element_blank()) +
  facet_wrap( ~ r1_label, scales = 'free_y') +
  labs(title = 'percent threatened')

```
