---
title: 'Fisheries and biodiversity intactness'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ohibc/src/templates/ohibc_hdr1.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}

knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'Figs/',
                      echo = TRUE, message = FALSE, warning = FALSE)

library(raster)
library(data.table)

source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')
  ### includes library(tidyverse); library(stringr); 
  ### dir_M points to ohi directory on Mazu; dir_O points to home dir on Mazu

dir_git <- '~/github/spp_risk_dists'

### goal specific folders and info
dir_setup <- file.path(dir_git, 'data_setup')
dir_data  <- file.path(dir_git, 'data')
dir_o_anx <- file.path(dir_O, 'git-annex/spp_risk_dists')

source(file.path(dir_git, 'data_setup/api_fxns.R'))

```

# Summary

Compare fisheries to biodiversity intactness: 

# Methods


## Compare Fisheries effort to various metrics

``` {r rerasterize_gfw, eval = FALSE}
### adjust JC's rasters to our grid.  Only need to do this once!
rast_base <- raster(resolution = 0.1, ext = extent(c(-180, 180, -90, 90)))
r1 <- raster(file.path(dir_data, 'gfw_data', 'monthly_mean_fishing_hours_casey.grd'))
r1_reproj <- projectRaster(r1, rast_base, method = 'ngb')
writeRaster(r1_reproj, file.path(dir_data, 'gfw_data', 'monthly_mean_fishing_hours.tif'),
            overwrite = TRUE)

r2 <- raster(file.path(dir_data, 'gfw_data', 'total_fishing_hours_casey.grd'))
r2_reproj <- projectRaster(r2, rast_base, method = 'ngb')
writeRaster(r2_reproj, file.path(dir_data, 'gfw_data', 'total_fishing_hours.tif'),
            overwrite = TRUE)
```

``` {r, eval = FALSE}
### is monthly mean proportional to total?
r_m <- raster(file.path(dir_data, 'gfw_data', 'monthly_mean_fishing_hours.tif'))
r_t <- raster(file.path(dir_data, 'gfw_data', 'total_fishing_hours.tif'))

x <- r_t / r_m
plot(x)

### NOPE.  Maybe seasonal differences?  For our purposes, let's use total.
```

``` {r}

### create log total raster to go along with total fishing hours raster.  
log_rast_file <- file.path(dir_data, 'gfw_data', 'log_total_fishing_hours.tif')
if(!file.exists(log_rast_file)) {
  r <- raster(file.path(dir_data, 'gfw_data', 'total_fishing_hours.tif'))
  log_r <- log(r)
  writeRaster(log_r, log_rast_file)
}
```

``` {r set up mpa and values dataframe}

mean_rast     <- raster(file.path(dir_git, 'output', 'mean_risk_raster_010deg.tif'))
var_rast      <- raster(file.path(dir_git, 'output', 'var_risk_raster_010deg.tif'))
n_spp_rast    <- raster(file.path(dir_git, 'output', 'n_spp_risk_raster_010deg.tif'))
n_threat_rast <- raster(file.path(dir_git, 'output', 'n_threat_raster_010deg.tif'))
trend_rast    <- raster(file.path(dir_git, 'output', 'trend_raster_010deg.tif'))
eez_rast      <- raster(file.path(dir_git, 'spatial', 'eez_rast_010_wgs84.tif'))
f_rast        <- raster(file.path(dir_data, 'gfw_data', 'total_fishing_hours.tif'))
ln_f_rast     <- raster(file.path(dir_data, 'gfw_data', 'log_total_fishing_hours.tif'))

# tmp_rast <- calc(eez_rast, fun = function(x) x %in% c(1:212, 214:255))
### excludes high seas and antarctica

risk_f_df <- data.frame(cell_id     = 1:length(values(mean_rast)),
                        rgn_id      = values(eez_rast),
                        mean_risk   = values(mean_rast),
                        var_risk    = values(var_rast),
                        n_spp       = values(n_spp_rast),
                        n_threat    = values(n_threat_rast),
                        mean_trend  = values(trend_rast),
                        f_effort    = values(f_rast),
                        ln_f_effort = values(ln_f_rast)) %>%
  filter(!is.na(mean_risk)) %>%
  left_join(read_csv(file.path(dir_git, 'spatial/rgn_names.csv')), by = c('rgn_id'))

```

### Fishing effort (log) vs. mean risk and variance

``` {r examine f vs risk}

f_vs_risk_df <- risk_f_df %>%
  select(mean_risk, f_effort, ln_f_effort, n_spp, var_risk, r1_label) %>%
  distinct() %>%
  sample_n(10000)

# ggplot(f_vs_risk_df, aes(x = f_effort, y = mean_risk)) +
#   ggtheme_plot() +
#   geom_point(aes(color = n_spp), alpha = .2)

ggplot(f_vs_risk_df, aes(x = ln_f_effort, y = mean_risk)) +
  ggtheme_plot() +
  geom_point(alpha = .2, aes(color = var_risk)) +
  scale_color_distiller(palette = 'YlGnBu') +
  facet_wrap( ~ r1_label) +
  labs(title = 'mean risk vs. log fishing effort')

ggplot(f_vs_risk_df, aes(x = ln_f_effort, y = var_risk)) +
  ggtheme_plot() +
  geom_point(alpha = .2) +
  facet_wrap( ~ r1_label) +
  labs(title = 'variance of risk vs. log fishing effort')

```

### Fishing effort (log) vs. range-rarity-weighted mean risk and variance


``` {r set up f and rr-values dataframe}

mean_rr_rast      <- raster(file.path(dir_git, 'output', 'mean_rr_risk_raster_010deg.tif'))
# var_rr_rast     <- raster(file.path(dir_git, 'output', 'var_rr_risk_raster_010deg.tif'))
sr_rr_rast        <- raster(file.path(dir_git, 'output', 'sr_rr_risk_raster_010deg.tif'))
sr_rr_threat_rast <- raster(file.path(dir_git, 'output', 'sr_rr_threat_raster_010deg.tif'))
trend_rr_rast     <- raster(file.path(dir_git, 'output', 'trend_rr_raster_010deg.tif'))
eez_rast          <- raster(file.path(dir_git, 'spatial', 'eez_rast_010_wgs84.tif'))
mpa_df            <- read_csv(file.path(dir_git, 'spatial', 'wdpa_mpa_area_010_wgs84.csv'))

# tmp_rast <- calc(eez_rast, fun = function(x) x %in% c(1:212, 214:255))
### excludes high seas and antarctica

rr_risk_f_df <- data.frame(cell_id       = 1:length(values(mean_rast)),
                           rgn_id        = values(eez_rast),
                           mean_rr_risk  = values(mean_rr_rast),
                           # var_risk    = values(var_rr_rast),
                           sr_rr_risk    = values(sr_rr_rast),
                           sr_rr_threat  = values(sr_rr_threat_rast),
                           mean_rr_trend = values(trend_rr_rast),
                           f_effort      = values(f_rast),
                           ln_f_effort   = values(ln_f_rast)) %>%
  filter(!is.na(mean_rr_risk)) %>%
  left_join(read_csv(file.path(dir_git, 'spatial/rgn_names.csv')), by = c('rgn_id'))

```


``` {r examine f vs risk}

f_vs_rr_risk_df <- rr_risk_f_df %>%
  select(mean_rr_risk, f_effort, ln_f_effort, sr_rr_risk, r1_label) %>%
  distinct() %>%
  sample_n(10000)

# ggplot(f_vs_risk_df, aes(x = f_effort, y = mean_risk)) +
#   ggtheme_plot() +
#   geom_point(aes(color = n_spp), alpha = .2)

ggplot(f_vs_rr_risk_df, aes(x = ln_f_effort, y = mean_rr_risk)) +
  ggtheme_plot() +
  geom_point(alpha = .2) +
  facet_wrap( ~ r1_label) +
  labs(title = 'range-rarity-weighted mean risk vs. log fishing effort')

# ggplot(f_vs_risk_df, aes(x = ln_f_effort, y = var_risk)) +
#   ggtheme_plot() +
#   geom_point(alpha = .2) +
#   facet_wrap( ~ r1_label) +
#   labs(title = 'variance of risk vs. log fishing effort')

```

``` {r examine f vs rr-risk}

```
