---
title: 'Crosstab rasters for analysis'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ohibc/src/templates/ohibc_hdr1.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}

knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'Figs/',
                      echo = TRUE, message = FALSE, warning = FALSE)

library(raster)
library(sf)
library(fasterize)

source('~/github/src/R/common.R')  ###
  ### includes library(tidyverse); library(stringr); dir_M points to ohi directory

dir_git <- '~/github/spp_health_dists'

### goal specific folders and info
dir_setup   <- file.path(dir_git, 'data_setup')
dir_spatial <- file.path(dir_git, 'spatial')
dir_anx     <- file.path(dir_M, 'git-annex')
dir_o_anx   <- file.path(dir_O, 'git-annex/spp_health_dists')
# ### provenance tracking
library(provRmd); prov_setup()

### support scripts
source('~/github/src/R/rast_tools.R') 
  ### raster plotting and analyzing scripts

### bring in ocean raster (all 1 or NA values)
ocean_base <- raster(file.path(dir_M, 'model/GL-NCEAS-Halpern2008/tmp/ocean.tif'))

```

# Summary

Using the LOICZID raster and rasters of WDPA and MEOW regions, create crosstabs of AquaMaps cells per each zone or protection year

# Data Sources

# Methods

## Cross tab each raster to LOICZID

Create ocean area to loiczid lookup just to compare areas to AquaMaps values
``` {r crosstab_ocean_area}

loiczid_moll    <- raster(file.path(dir_o_anx, 'spatial/loiczid_moll_934m.tif'))

ocean_area_lookup_file <- file.path(dir_git, 'data/ocean_area_lookup.csv')
if(!file.exists(ocean_area_lookup_file)) {
  ocean_xtab <- crosstab(loiczid_moll, 
                                ocean_base, 
                                progress = 'text',
                                useNA = TRUE)
  
  ocean_area_lookup <- ocean_xtab %>%
    as.data.frame() %>%
    setNames(c('loiczid', 'ocean_flag', 'cells')) %>%
    filter(cells > 0 & !is.na(loiczid)) %>%
    mutate(ocean_area_km2 = cells / (.934^2)) %>%
    select(-ocean_flag, -cells)
  
  write_csv(ocean_area_lookup, ocean_area_lookup_file)
} 

ocean_area_lookup <- read_csv(ocean_area_lookup_file)

```


``` {r crosstab_wdpa_marine_all}

loiczid_moll    <- raster(file.path(dir_o_anx, 'spatial/loiczid_moll_934m.tif'))
wdpa_marine_all <- raster(file.path(dir_o_anx, 'wdpa/wdpa_mar_all_dec2017.tif'))

wdpa_mar_all_lookup_file <- file.path(dir_git, 'data/wdpa_mar_all_lookup.csv')
if(!file.exists(wdpa_mar_all_lookup_file)) {
  wdpa_mar_all_xtab <- crosstab(loiczid_moll, 
                                wdpa_marine_all, 
                                progress = 'text',
                                useNA = TRUE)
  
  wdpa_mar_all_lookup <- wdpa_mar_all_xtab %>%
    as.data.frame() %>%
    setNames(c('loiczid', 'year', 'cells')) %>%
    filter(cells > 0 & !is.na(loiczid)) %>%
    filter(!is.na(year)) %>%
    mutate(wdpa_yr_km2 = cells / (.934^2)) %>%
    select(-cells)
  
  write_csv(wdpa_mar_all_lookup, wdpa_mar_all_lookup_file)
} 

```

``` {r crosstab_wdpa_marine_1-6}

loiczid_moll     <- raster(file.path(dir_o_anx, 'spatial/loiczid_moll_934m.tif'))
wdpa_marine_i_vi <- raster(file.path(dir_o_anx, 'wdpa/wdpa_mar_i_vi_dec2017.tif'))

wdpa_i_vi_lookup_file <- file.path(dir_git, 'data/wdpa_i_vi_lookup.csv')

if(!file.exists(wdpa_i_vi_lookup_file)) {
  wdpa_i_vi_xtab <- crosstab(loiczid_moll, 
                             wdpa_marine_i_vi, 
                             progress = 'text', 
                             useNA = TRUE)
  
  wdpa_i_vi_lookup <- wdpa_i_vi_xtab %>%
    as.data.frame() %>%
    setNames(c('loiczid', 'year', 'cells')) %>%
    filter(cells > 0 & !is.na(loiczid)) %>%
    filter(!is.na(year)) %>%
    mutate(wdpa_yr_km2 = cells / (.934^2)) %>%
    select(-cells)  
  
  write_csv(wdpa_i_vi_lookup, wdpa_i_vi_lookup_file)
}


```

``` {r crosstab_wdpa_marine_1-4}

loiczid_moll     <- raster(file.path(dir_o_anx, 'spatial/loiczid_moll_934m.tif'))
wdpa_marine_i_iv <- raster(file.path(dir_o_anx, 'wdpa/wdpa_mar_i_iv_dec2017.tif'))

wdpa_i_iv_lookup_file <- file.path(dir_git, 'data/wdpa_i_iv_lookup.csv')
if(!file.exists(wdpa_i_iv_lookup_file)) {
  wdpa_i_iv_xtab <- crosstab(loiczid_moll, 
                             wdpa_marine_i_iv, 
                             progress = 'text', 
                             useNA = TRUE)

  wdpa_i_iv_lookup <- wdpa_i_iv_xtab %>%
    as.data.frame() %>%
    setNames(c('loiczid', 'year', 'cells')) %>%
    filter(cells > 0 & !is.na(loiczid)) %>%
    filter(!is.na(year)) %>%
    mutate(wdpa_yr_km2 = cells / (.934^2)) %>%
    select(-cells)
  write_csv(wdpa_i_iv_lookup, wdpa_i_iv_lookup_file)
}

```

``` {r crosstab_meow}

loiczid_moll <- raster(file.path(dir_o_anx, 'spatial/loiczid_moll_934m.tif'))
meow_rast    <- raster(file.path(dir_o_anx, 'meow/meow_rast_934m.tif'))

meow_lookup_file <- file.path(dir_git, 'data/meow_lookup.csv')
if(!file.exists(meow_lookup_file)) {
  meow_xtab <- crosstab(loiczid_moll, 
                          meow_rast, 
                          useNA = TRUE, progress = 'text')
  
  meow_lookup <- meow_xtab %>%
    as.data.frame() %>%
    setNames(c('loiczid', 'eco_code', 'cells')) %>%
    filter(cells > 0 & !is.na(loiczid)) %>%
    filter(!is.na(eco_code)) %>%
    select(-cells)
  
  write_csv(meow_lookup, meow_lookup_file)
}

```

-----

``` {r prov_footer, results = 'asis'}
prov_wrapup(commit_outputs = FALSE)
```

