---
title: 'Biodiversity risk maps'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ohibc/src/templates/ohibc_hdr1.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}

knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'figs/',
                      echo = TRUE, message = FALSE, warning = FALSE)

library(raster)
library(data.table)
library(sf)


source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')  ###
  ### includes library(tidyverse); library(stringr); dir_M points to ohi directory

dir_git <- '~/github/spp_risk_dists'

### goal specific folders and info
dir_setup <- file.path(dir_git, '_setup')
dir_data  <- file.path(dir_git, '_data')
dir_o_anx <- file.path(dir_O, 'git-annex/spp_risk_dists')

source(file.path(dir_setup, 'common_fxns.R'))

```

## generate rasters from csvs for a few key species

``` {r mean_risk_raster}

spp_maps <- list.files(file.path(dir_git, 'pres_figs/rast'), full.names = TRUE)

rast_base <- raster(file.path(dir_git, '_spatial', 'cell_id_rast.tif'))

land_poly <- sf::read_sf(file.path(dir_git, '_spatial/ne_10m_land/ne_10m_land.shp')) %>%
  st_transform(gp_proj4)

for(spp_map in spp_maps) {
  ### spp_map <- spp_maps[1]
  spp_tif <- basename(spp_map %>% str_replace('.csv', '.tif'))
  map_rast_file <- file.path(dir_git, 'pres_figs/rast', spp_tif)
  if(!file.exists(map_rast_file) | reload == TRUE) {
    cell_summary <- read_csv(spp_map)
  
    mean_rast <- subs(rast_base, cell_summary, by = 'cell_id', which = 'mean_risk')
    writeRaster(mean_rast, map_rast_file,
                overwrite = TRUE)
  
  ### mean_rast <- raster(file.path(dir_git, 'output', 'mean_risk_raster_comp.tif'))
  
  } else {
    message('Map exists: ', map_rast_file)
  }
}

```

